### PR TITLE
v0.1.13 release

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

We need to update zcash_script's C++ and Rust dependencies.

This is still missing the version bumps.

Part of https://github.com/ZcashFoundation/zebra/issues/7071.

### CODE REVIEW

**Comment by arya2** [comment]
>  cargo:warning=In file included from depend/zcash/src/zcash/NoteEncryption.hpp:13,
>   cargo:warning=                 from depend/zcash/src/primitives/transaction.h:22,
>   cargo:warning=                 from depend/zcash/src/script/zcash_script.cpp:10:
>   cargo:warning=depend/zcash/src/zcash/memo.h:8:10: fatal error: tl/expected.hpp: No such file or directory
>   cargo:warning=    8 | #include <tl/expected.hpp>
> 
> https://github.com/ZcashFoundation/zcash_script/actions/runs/5393931206/jobs/9794369997?pr=91#step:4:651

https://github.com/zcash/zcash/issues/6716

**Comment by conradoplg** [comment]
Do you need help making this build?

I added the `expected.hpp`, luckily it seems just a header-only library. But we need to update the zcash_script instructions with how to update it (basically get the version pointed to in `./zcash/depends/packages/tl_expected.mk` and copy the header to `depend/expected/include/tl/expected.hpp`. Or we could use subtree to include the library, but seems overkill.

But there is still another build issue, which seem to be related to crate versions discrepancy. Let me know if you need more help.

**Comment by arya2** [comment]
> Do you need help making this build?

Yes please.

**Comment by conradoplg** [comment]
> > Do you need help making this build?
> 
> Yes please.

I think I got it working!

**Review by teor2345 — DISMISSED** [review]
Thanks, looks good!

Let's release it.

**Review by conradoplg — APPROVED** [review]

**Pull request merged**
