### PR TITLE
Upgrade zcash_script to zcashd v5.5.0

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We want to upgrade to the same dependencies as `zcashd` 5.5.0, to avoid duplicate dependencies.

Part of this upgrade has already happened in Zebra:
https://github.com/ZcashFoundation/zebra/pull/6536

## Changes

- Follow the release instructions and do the standard update steps
- [Update bridge file list to match the latest zcashd](https://github.com/ZcashFoundation/zcash_script/commit/42eb14e6229b6574a7ce02a3ed599d60a5048400)
- [Add additional Rust dependencies needed to compile](https://github.com/ZcashFoundation/zcash_script/commit/0ee772e5d110085ca18eb0b34902150cda7d1cd6)

Minor fixes:
- [Add extra info to cxx_gen errors](https://github.com/ZcashFoundation/zcash_script/commit/73e2984372d8f1097daf86cb8286415a0946f3a0)
- [Silence a C compiler macro redefinition warning](https://github.com/ZcashFoundation/zcash_script/commit/65cef26a71d88c2a60ccb31b627e1b968d9dd621)
- [Add module docs for the build script to avoid warnings](https://github.com/ZcashFoundation/zcash_script/commit/4a918e480cd88d5a797a7e90e7c0bbfc85001ac6)
- [Ignore some expected clippy lints](https://github.com/ZcashFoundation/zcash_script/pull/84/commits/f91533863c1dbd4b140af3bcc3da911017e725b4)
- [Standardise directory include paths in Cargo.toml](https://github.com/ZcashFoundation/zcash_script/commit/49f4dfc5bb4df14df5936db72e51fc346154238c)
- [Standardise directory paths in build.rs](https://github.com/ZcashFoundation/zcash_script/pull/84/commits/07418ff6790ff625d34a91bed317dc4a831e604c)
- [Ignore some emacs temporary files](https://github.com/ZcashFoundation/zcash_script/commit/36e05801168b764c4d6f17a52aa46f723e1f57ed)

## Review

This PR contains a copy of the `zcashd` changes since the last zcash_script update.

You can review the non-zcashd changes here:
- https://github.com/ZcashFoundation/zcash_script/pull/84/files/f7113a2070c882dda501364f654898cf9c475026

### CODE REVIEW

**Comment by teor2345** [comment]
This currently works for builds and releases, but not for tests.

When I run `cargo test`, I get linker errors like:
```
"-Wl,-Bdynamic" "-lstdc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/dev/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/dev/zcash_script/target/debug/deps/zcash_script-2f81ce53335cc20b" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"                                                       
  = note: /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/libzcash_script.a(zcash_script.o): in function `rust::cxxbridge1::Box<orchard_bundle::Bundle>::~Box()':                                                                                                                                                       
          /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/include/rust/cxx.h:760: undefined reference to `rust::cxxbridge1::Box<orchard_bundle::Bundle>::drop()'               
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/libzcash_script.a(zcash_script.o): in function `OrchardBundle::OrchardBundle(OrchardBundle const&)':                                                                                                                                                          
          /home/dev/zcash_script/depend/zcash/src/primitives/orchard.h:42: undefined reference to `orchard_bundle::Bundle::box_clone() const'                                                              
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/libzcash_script.a(zcash_script.o): in function `rust::cxxbridge1::Box<stream::CppStream>::~Box()':                                                                                                                                                            
          /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/include/rust/cxx.h:760: undefined reference to `rust::cxxbridge1::Box<stream::CppStream>::drop()'                    
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/libzcash_script.a(zcash_script.o): in function `void OrchardBundle::Serialize<CSizeComputer>(CSizeComputer&) const':                                                                                                                                          
          /home/dev/zcash_script/depend/zcash/src/primitives/orchard.h:71: undefined reference to `orchard_bundle::Bundle::serialize(stream::CppStream&) const'                                            
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/depend/zcash/src/primitives/orchard.h:71: undefined reference to `ToRustStream(CSizeComputer&)'         
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/libzcash_script.a(zcash_script.o): in function `void OrchardBundle::Unserialize<CBaseDataStream<std::vector<char, zero_after_free_allocator<char> > > >(CBaseDataStream<std::vector<char, zero_after_free_allocator<char> > >&)':                             
          /home/dev/zcash_script/depend/zcash/src/primitives/orchard.h:80: undefined reference to `ToRustStream(CBaseDataStream<std::vector<char, zero_after_free_allocator<char> > >&)'                   
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/depend/zcash/src/primitives/orchard.h:80: undefined reference to `orchard_bundle::parse(stream::CppStream&)'                                                                                                                                                                                                       
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/libzcash_script.a(zcash_script.o): in function `rust::cxxbridge1::Box<orchard_bundle::Bundle>::operator=(rust::cxxbridge1::Box<orchard_bundle::Bundle>&&) &':                                                                                                 
          /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/include/rust/cxx.h:767: undefined reference to `rust::cxxbridge1::Box<orchard_bundle::Bundle>::drop()'               
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/libzcash_script.a(transaction.o): in function `OrchardBundle::OrchardBundle()':                                                                                                                                                                               
          /home/dev/zcash_script/depend/zcash/src/primitives/orchard.h:37: undefined reference to `orchard_bundle::none()'                                                                                 
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/target/debug/build/zcash_script-c13e79cb66fd76cc/out/libzcash_script.a(transaction.o): in function `void OrchardBundle::Serialize<CBaseDataStream<std::vector<char, zero_after_free_allocator<char> > > >(CBaseDataStream<std::vector<char, zero_after_free_allocator<char> > >&) const':                          
          /home/dev/zcash_script/depend/zcash/src/primitives/orchard.h:71: undefined reference to `ToRustStream(CBaseDataStream<std::vector<char, zero_after_free_allocator<char> > >&)'                   
          /nix/store/8qsl7gmnjsg7n460ll32flz5fzlk2kd7-binutils-2.38/bin/ld: /home/dev/zcash_script/depend/zcash/src/primitives/orchard.h:71: undefined reference to `orchard_bundle::Bundle::serialize(stream::CppStream&) const'                                                                                                                                                                                     
          collect2: error: ld returned 1 exit status                                                                                                                          
```

But the missing functions are bridged here:
https://github.com/zcash/zcash/blob/035e21a61051a5d3b909e6d3d0606bc28d9857ef/src/rust/src/bridge.rs#L216

And defined here:
https://github.com/zcash/zcash/blob/035e21a61051a5d3b909e6d3d0606bc28d9857ef/src/rust/src/orchard_bundle.rs#L80-L82

I tried adding the generated `rust/bridge.c` to the list of files (like `rust/blake2b.c`), but it wouldn't compile. It seemed to be missing some important C++ headers.

**Comment by teor2345** [comment]
@conradoplg can you help fix these zcash_script linker errors?

**Comment by conradoplg** [comment]
> @conradoplg can you help fix these zcash_script linker errors?

Fixed, assuming CI passes. Indeed the linking error was from not including `bridge.c`. The include error after fixing that was caused by our `build.rs` generating the .c and .h in the same folder, which was making `bridge.c` pick up the wrong header with `#include "streams.h"` (it was picking up the generated one, instead of `zcash/src/streams.h`). I fixed it by generating them in different folders, like zcashd does (can't remember why I didn't do that in the first place)

**Comment by teor2345** [comment]
Thank you so much for this!

**Comment by teor2345** [comment]
This is waiting on the zcashd 5.5.0 release:
https://github.com/zcash/zcash/tags

**Comment by teor2345** [comment]
This is now updated for `zcashd` v5.5.0-rc1. We're waiting on the stable release before we do our release.

**Comment by daira** [comment]
`zcashd` v5.5.0 has been tagged, and includes https://github.com/zcash/zcash/pull/6597 and https://github.com/zcash/zcash/pull/6596 (as part of https://github.com/zcash/zcash/pull/6606).

**Comment by daira** [comment]
I notice you're linking with `-lstdc++`, i.e. libstdc++, whereas zcashd uses libc++. I'm not sure that matters if you're recompiling the script code, just thought I'd point it out.

**Comment by teor2345** [comment]
> I notice you're linking with `-lstdc++`, i.e. libstdc++, whereas zcashd uses libc++. I'm not sure that matters if you're recompiling the script code, just thought I'd point it out.

Thanks, I opened ticket #85 for this.

**Review by conradoplg — APPROVED** [review]

**Pull request merged**
